"""initial schema

Revision ID: cb2c7fecfd19
Revises: 
Create Date: 2026-04-01 18:05:54.471960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb2c7fecfd19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender_enum'), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('height', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('max_bpm', sa.Integer(), nullable=False),
    sa.Column('avg_bpm', sa.Integer(), nullable=False),
    sa.Column('resting_bpm', sa.Integer(), nullable=False),
    sa.Column('session_duration', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('calories_burned', sa.Integer(), nullable=False),
    sa.Column('workout_type', sa.Enum('cardio', 'hiit', 'strength', 'yoga', name='workout_type_enum'), nullable=False),
    sa.Column('workout_frequency', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('experience_level', sa.Integer(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('carbs', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('proteins', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('fats', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('sugar_g', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('diet_type', sa.Enum('vegan', 'vegetarian', 'paleo', 'keto', 'low_carb', 'balanced', name='diet_type_enum'), nullable=False),
    sa.Column('daily_meals_frequency', sa.Integer(), nullable=False),
    sa.Column('water_intake', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('fat_class', sa.Enum('low', 'mid', 'high', name='fat_class_enum'), nullable=False),
    sa.Column('fat_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('age BETWEEN 1 AND 100', name='ck_prediction_history_age'),
    sa.CheckConstraint('avg_bpm BETWEEN 40 AND 200', name='ck_prediction_history_avg_bpm'),
    sa.CheckConstraint('calories BETWEEN 500 AND 10000', name='ck_prediction_history_calories'),
    sa.CheckConstraint('calories_burned BETWEEN 10 AND 5000', name='ck_prediction_history_calories_burned'),
    sa.CheckConstraint('daily_meals_frequency BETWEEN 1 AND 10', name='ck_prediction_history_daily_meals_frequency'),
    sa.CheckConstraint('experience_level BETWEEN 1 AND 3', name='ck_prediction_history_experience_level'),
    sa.CheckConstraint('fat_percentage BETWEEN 0 AND 100', name='ck_prediction_history_fat_percentage'),
    sa.CheckConstraint('height BETWEEN 0.2 AND 2.72', name='ck_prediction_history_height'),
    sa.CheckConstraint('max_bpm BETWEEN 60 AND 230', name='ck_prediction_history_max_bpm'),
    sa.CheckConstraint('resting_bpm BETWEEN 30 AND 120', name='ck_prediction_history_resting_bpm'),
    sa.CheckConstraint('session_duration BETWEEN 0.1 AND 3.0', name='ck_prediction_history_session_duration'),
    sa.CheckConstraint('water_intake BETWEEN 0 AND 20', name='ck_prediction_history_water_intake'),
    sa.CheckConstraint('weight BETWEEN 2 AND 635', name='ck_prediction_history_weight'),
    sa.CheckConstraint('workout_frequency BETWEEN 0 AND 14', name='ck_prediction_history_workout_frequency'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_history_created_at'), 'prediction_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_prediction_history_fat_class'), 'prediction_history', ['fat_class'], unique=False)
    op.create_index(op.f('ix_prediction_history_id'), 'prediction_history', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_history_model_version'), 'prediction_history', ['model_version'], unique=False)
    op.create_table('prediction_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('is_prediction_close', sa.Boolean(), nullable=True),
    sa.Column('actual_fat_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('consent_to_retrain', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('consent_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_fat_percentage IS NULL OR actual_fat_percentage BETWEEN 0 AND 100', name='ck_prediction_feedback_actual_fat_percentage_range'),
    sa.CheckConstraint('rating BETWEEN 0 AND 10', name='ck_prediction_feedback_rating_range'),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_feedback_id'), 'prediction_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_feedback_prediction_id'), 'prediction_feedback', ['prediction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_feedback_prediction_id'), table_name='prediction_feedback')
    op.drop_index(op.f('ix_prediction_feedback_id'), table_name='prediction_feedback')
    op.drop_table('prediction_feedback')
    op.drop_index(op.f('ix_prediction_history_model_version'), table_name='prediction_history')
    op.drop_index(op.f('ix_prediction_history_id'), table_name='prediction_history')
    op.drop_index(op.f('ix_prediction_history_fat_class'), table_name='prediction_history')
    op.drop_index(op.f('ix_prediction_history_created_at'), table_name='prediction_history')
    op.drop_table('prediction_history')
    # ### end Alembic commands ###
