# PREDICTION SERVICE CONSTANTS ----------------------------------------------
RAW_FEATURES: tuple[str, ...] = (
    "age",
    "gender",
    "weight",
    "height",
    "max_bpm",
    "avg_bpm",
    "resting_bpm",
    "session_duration",
    "calories_burned",
    "workout_type",
    "water_intake",
    "workout_frequency",
    "experience_level",
    "bmi",
    "daily_meals_frequency",
    "carbs",
    "proteins",
    "fats",
    "calories",
    "diet_type",
    "sugar_g",
    "fat_percentage",
)

MODEL_INPUT_FEATURES: tuple[str, ...] = RAW_FEATURES[:-1]

ENCODED_FEATURES: tuple[str, ...] = (
    "age",
    "weight",
    "height",
    "max_bpm",
    "avg_bpm",
    "resting_bpm",
    "session_duration",
    "calories_burned",
    "water_intake",
    "workout_frequency",
    "experience_level",
    "bmi",
    "daily_meals_frequency",
    "carbs",
    "proteins",
    "fats",
    "calories",
    "sugar_g",
    "gender_female",
    "gender_male",
    "workout_type_cardio",
    "workout_type_hiit",
    "workout_type_strength",
    "workout_type_yoga",
    "diet_type_balanced",
    "diet_type_keto",
    "diet_type_low-carb",
    "diet_type_paleo",
    "diet_type_vegan",
    "diet_type_vegetarian",
)

ENGINEERED_FEATURES: tuple[str, ...] = (
    "hrr",
    "intensity_ratio",
    "hrr_per_age",
    "weekly_training_minutes",
    "weekly_training_hours",
    "calories_per_training_hour",
    "calories_per_minute",
    "calories_per_kg",
    "bmi_x_age",
    "bmi_x_training_hours",
    "protein_ratio",
    "carb_ratio",
    "fat_ratio",
    "sugar_per_calorie",
    "calories_per_meal",
    "high_intensity_workout",
    "strength_vs_cardio",
    "intensity_weighted_training_hours",
    "low_carb_diet",
    "plant_based_diet",
    "female_x_bmi",
    "male_x_bmi",
    "log1p_calories_burned",
    "log1p_weekly_training_hours",
    "log1p_calories_per_training_hour",
    "log1p_calories_per_kg",
    "log1p_calories",
)

# The final model bundle was trained with these 57 columns in this exact order.
MODEL_FEATURES: tuple[str, ...] = ENCODED_FEATURES + ENGINEERED_FEATURES

FAT_CLASS_MAP: dict[int, str] = {
    0: "low",
    1: "mid",
    2: "high",
}
#--------------------------------------------------------------------------------------------
